catalogMode: strict
ignoreWorkspaceRootCheck: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - packages/*
  - packages/vue/demo

catalog:
  '@antfu/eslint-config': 7.3.0
  '@types/node': ^25.2.1
  '@vitejs/plugin-vue': ^6.0.4
  '@vitest/browser-playwright': ^4.0.18
  '@vitest/ui': ^4.0.18
  eslint: ^9.39.2
  fast-glob: ^3.3.3
  lightningcss: ^1.31.1
  playwright: ^1.58.2
  rollup: ^4.57.1
  tabbable: ^6.4.0
  tsdown: ^0.20.3
  typescript: ^5.9.3
  unplugin-lightningcss: ^0.4.5
  unplugin-vue: ^7.0.1
  vite: ^7.3.1
  vitepress: ^1.6.4
  vitest: ^4.0.18
  vue: ^3.5.27
  vue-tsc: ^3.2.4
onlyBuiltDependencies:
  - esbuild
